users:
  user1:
    username: elfgzp1
    hashPasswd: test
  user2:
    username: elfgzp2
    hashPasswd: test
  user3:
    username: elfgzp3
    hashPasswd: test
    admin: true
servers:
  server1:
    name: Local Test Server 1
    host: localhost
    port: 22
    sshUsers:
      sshUser1:
        sshUsername: gzp
        identityFile: ~/.ssh/localhost.pem
        allowUsers: [elfgzp1]
  server2:
    name: Local Test Server 2
    host: localhost
    port: 22
    sshUsers:
      sshUser1:
        sshUsername: gzp
        identityFile: ~/.ssh/localhost.pem
        allowUsers: [elfgzp2]
  server3:
    name: Local Test Server 3
    host: localhost
    port: 22
    sshUsers:
      sshUser1:
        sshUsername: gzp
        identityFile: ~/.ssh/localhost.pem
